
# grpc-server
    grpc_use_tls = false
    grpc_server_host = ""
    grpc_server_port = 10000

# metrics-server
    metrics_use_tls = false
    metrics_server_host =  ""
    metrics_server_port = 10001
    metrics_cache_size =  1024
    metrics_uri_path = "/metrics"

# gateway-proxy
    gateway_use_tls = false
    use_gateway_proxy = true
    gateway_proxy_host = ""
    gateway_proxy_port = 8080

# tls
    ca_cert_path = ""
    server_cert_path = ""
    server_key_path = ""
    server_cert_name = ""

# statsd
    report_statsd = false
    statsd_host = "127.0.0.1"
    statsd_port = 8125
    statsd_mem_interval = ""

# oauth
    use_oauth = false
    oauth_provider = ""
    oauth_client_id = ""

# zookeeper
    use_zk = false
    zk_connection_string = ""
    zk_announce_path=""
    zk_announce_host = ""

# misc
    verbose_logging = true
